//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("java:com.ladpc.commons.services", ClrNamespace="com.ladpc.commons.services")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("java:com.ladpc", ClrNamespace="com.ladpc")]

namespace com.ladpc.commons.services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemHeader", Namespace="java:com.ladpc.commons.services")]
    public partial class SystemHeader : object
    {
        
        private int CustomerField;
        
        private int RecipientField;
        
        private int SenderField;
        
        private string TokenField;
        
        private string TranIDField;
        
        private string UserIdField;
        
        private string UserPassField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Customer
        {
            get
            {
                return this.CustomerField;
            }
            set
            {
                this.CustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Recipient
        {
            get
            {
                return this.RecipientField;
            }
            set
            {
                this.RecipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TranID
        {
            get
            {
                return this.TranIDField;
            }
            set
            {
                this.TranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserPass
        {
            get
            {
                return this.UserPassField;
            }
            set
            {
                this.UserPassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnObject", Namespace="java:com.ladpc.commons.services")]
    public partial class ReturnObject : object
    {
        
        private com.ladpc.commons.services.Msg MsgField;
        
        private com.ladpc.commons.services.Globals GlobalsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public com.ladpc.commons.services.Msg Msg
        {
            get
            {
                return this.MsgField;
            }
            set
            {
                this.MsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public com.ladpc.commons.services.Globals Globals
        {
            get
            {
                return this.GlobalsField;
            }
            set
            {
                this.GlobalsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Msg", Namespace="java:com.ladpc.commons.services")]
    public partial class Msg : object
    {
        
        private string RcMessageField;
        
        private int RcNumberField;
        
        private int RcOwnerField;
        
        private int RcTypeField;
        
        private string RcVersionField;
        
        private string RcFieldNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RcMessage
        {
            get
            {
                return this.RcMessageField;
            }
            set
            {
                this.RcMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RcNumber
        {
            get
            {
                return this.RcNumberField;
            }
            set
            {
                this.RcNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RcOwner
        {
            get
            {
                return this.RcOwnerField;
            }
            set
            {
                this.RcOwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RcType
        {
            get
            {
                return this.RcTypeField;
            }
            set
            {
                this.RcTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RcVersion
        {
            get
            {
                return this.RcVersionField;
            }
            set
            {
                this.RcVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string RcFieldName
        {
            get
            {
                return this.RcFieldNameField;
            }
            set
            {
                this.RcFieldNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Globals", Namespace="java:com.ladpc.commons.services")]
    public partial class Globals : object
    {
        
        private string FileNetTokenField;
        
        private string IisIpField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FileNetToken
        {
            get
            {
                return this.FileNetTokenField;
            }
            set
            {
                this.FileNetTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IisIp
        {
            get
            {
                return this.IisIpField;
            }
            set
            {
                this.IisIpField = value;
            }
        }
    }
}
namespace com.ladpc
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfJavaLangstring_literal", Namespace="java:com.ladpc", ItemName="JavaLangstring")]
    public class ArrayOfJavaLangstring_literal : System.Collections.Generic.List<string>
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://com/ladpc", ConfigurationName="PortalSmsManagerWS")]
public interface PortalSmsManagerWS
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<addSmsRequestResponse> addSmsRequestAsync(addSmsRequestRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class addSmsRequestRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="addSmsRequest", Namespace="http://com/ladpc", Order=0)]
    public addSmsRequestRequestBody Body;
    
    public addSmsRequestRequest()
    {
    }
    
    public addSmsRequestRequest(addSmsRequestRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://com/ladpc")]
public partial class addSmsRequestRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public com.ladpc.commons.services.SystemHeader systemHeader;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string smsText;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public bool onlyIsraelPhones;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public com.ladpc.ArrayOfJavaLangstring_literal phones;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string requestKey;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    public bool withPostConfirmation;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
    public string scheduledDate;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
    public string smsTTSInMinutes;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
    public string smsTTLInMinutes;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
    public string smsSender;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
    public string smsSignature;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
    public string smsRateType;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
    public string smsSpecificRate;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
    public string smsSystemRate;
    
    public addSmsRequestRequestBody()
    {
    }
    
    public addSmsRequestRequestBody(com.ladpc.commons.services.SystemHeader systemHeader, string smsText, bool onlyIsraelPhones, com.ladpc.ArrayOfJavaLangstring_literal phones, string requestKey, bool withPostConfirmation, string scheduledDate, string smsTTSInMinutes, string smsTTLInMinutes, string smsSender, string smsSignature, string smsRateType, string smsSpecificRate, string smsSystemRate)
    {
        this.systemHeader = systemHeader;
        this.smsText = smsText;
        this.onlyIsraelPhones = onlyIsraelPhones;
        this.phones = phones;
        this.requestKey = requestKey;
        this.withPostConfirmation = withPostConfirmation;
        this.scheduledDate = scheduledDate;
        this.smsTTSInMinutes = smsTTSInMinutes;
        this.smsTTLInMinutes = smsTTLInMinutes;
        this.smsSender = smsSender;
        this.smsSignature = smsSignature;
        this.smsRateType = smsRateType;
        this.smsSpecificRate = smsSpecificRate;
        this.smsSystemRate = smsSystemRate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class addSmsRequestResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="addSmsRequestResponse", Namespace="http://com/ladpc", Order=0)]
    public addSmsRequestResponseBody Body;
    
    public addSmsRequestResponse()
    {
    }
    
    public addSmsRequestResponse(addSmsRequestResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://com/ladpc")]
public partial class addSmsRequestResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public com.ladpc.commons.services.ReturnObject @return;
    
    public addSmsRequestResponseBody()
    {
    }
    
    public addSmsRequestResponseBody(com.ladpc.commons.services.ReturnObject @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface PortalSmsManagerWSChannel : PortalSmsManagerWS, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class PortalSmsManagerWSClient : System.ServiceModel.ClientBase<PortalSmsManagerWS>, PortalSmsManagerWS
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public PortalSmsManagerWSClient() : 
            base(PortalSmsManagerWSClient.GetDefaultBinding(), PortalSmsManagerWSClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.PortalSmsManagerWSSoapPort.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PortalSmsManagerWSClient(EndpointConfiguration endpointConfiguration) : 
            base(PortalSmsManagerWSClient.GetBindingForEndpoint(endpointConfiguration), PortalSmsManagerWSClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PortalSmsManagerWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(PortalSmsManagerWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PortalSmsManagerWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(PortalSmsManagerWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PortalSmsManagerWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<addSmsRequestResponse> PortalSmsManagerWS.addSmsRequestAsync(addSmsRequestRequest request)
    {
        return base.Channel.addSmsRequestAsync(request);
    }
    
    public System.Threading.Tasks.Task<addSmsRequestResponse> addSmsRequestAsync(com.ladpc.commons.services.SystemHeader systemHeader, string smsText, bool onlyIsraelPhones, com.ladpc.ArrayOfJavaLangstring_literal phones, string requestKey, bool withPostConfirmation, string scheduledDate, string smsTTSInMinutes, string smsTTLInMinutes, string smsSender, string smsSignature, string smsRateType, string smsSpecificRate, string smsSystemRate)
    {
        addSmsRequestRequest inValue = new addSmsRequestRequest();
        inValue.Body = new addSmsRequestRequestBody();
        inValue.Body.systemHeader = systemHeader;
        inValue.Body.smsText = smsText;
        inValue.Body.onlyIsraelPhones = onlyIsraelPhones;
        inValue.Body.phones = phones;
        inValue.Body.requestKey = requestKey;
        inValue.Body.withPostConfirmation = withPostConfirmation;
        inValue.Body.scheduledDate = scheduledDate;
        inValue.Body.smsTTSInMinutes = smsTTSInMinutes;
        inValue.Body.smsTTLInMinutes = smsTTLInMinutes;
        inValue.Body.smsSender = smsSender;
        inValue.Body.smsSignature = smsSignature;
        inValue.Body.smsRateType = smsRateType;
        inValue.Body.smsSpecificRate = smsSpecificRate;
        inValue.Body.smsSystemRate = smsSystemRate;
        return ((PortalSmsManagerWS)(this)).addSmsRequestAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PortalSmsManagerWSSoapPort))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PortalSmsManagerWSSoapPort))
        {
            return new System.ServiceModel.EndpointAddress("http://vprdproactc.iula.org.il:7021/PortalSmsManagerWS_PS");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return PortalSmsManagerWSClient.GetBindingForEndpoint(EndpointConfiguration.PortalSmsManagerWSSoapPort);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return PortalSmsManagerWSClient.GetEndpointAddress(EndpointConfiguration.PortalSmsManagerWSSoapPort);
    }
    
    public enum EndpointConfiguration
    {
        
        PortalSmsManagerWSSoapPort,
    }
}
